version: 2.1

jobs:
  check-and-build-only:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME

orbs:
  docker: circleci/docker@1.5.0

workflows:
  build-docker-image-only:
    jobs:
      - check-and-build-only
